name: Deploy to AWS Lambda

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build --if-present

      - name: Zip Lambda package
        run: |
          zip -r function.zip . \
            -x ".git/*" ".github/*" "README.md"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<AWS_ACCOUNT_ID>:role/github-lambda-deploy-role
          aws-region: eu-west-2

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name bookings-node \
            --zip-file fileb://function.zip